server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MAIN?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: rootpassword
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: false

batch:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/MAIN?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
      username: root
      password: rootpassword
      maximum-pool-size: 2
