server:
  port: 8080
spring:
  batch:
    jdbc:
      table-prefix: GCP_         # Spring Batch에서 사용할 테이블 접두사
      initialize-schema: always  # 또는 운영에서는 never/embedded로 설정
      schema: classpath:custom-schema-mysql.sql
  datasource:
    main:
      pool-name: main-db
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/MAIN?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
      username: root
      password: rootpassword
    batch:
      pool-name: batch-db
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/BATCH?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
      username: root
      password: rootpassword
  jpa:
    hibernate:
      ddl-auto: update   # 엔티티 기반 테이블은 MAIN DB에 생성됨
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: false